<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="anonymous" failures="1" tests="6" name="example.Testing" time="0.024" errors="0" timestamp="2021-03-01T20:21:48 IST" skipped="2">
  <testcase classname="example.Testing" name="test7" time="0.001"/>
  <system-out/>
  <testcase classname="example.Testing" name="test6" time="0.002"/>
  <system-out/>
  <testcase classname="example.Testing" name="testss" time="0.001"/>
  <system-out/>
  <testcase classname="example.Testing" name="test5" time="0.000">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="example.Testing" name="tests" time="0.020">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at example.Testing.tests(Testing.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:70)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- tests -->
  <system-out/>
  <testcase classname="example.Testing" name="test8">
    <skipped/>
  </testcase> <!-- test8 -->
  <system-out/>
</testsuite> <!-- example.Testing -->
